-- Supabase SQL Setup for WasteFreeBD RBAC System
-- Execute these queries in your Supabase SQL Editor

-- 1. Create signin table
CREATE TABLE IF NOT EXISTS public.signin (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email character varying not null,
  password character varying null,
  "Name" text not null,
  role character varying not null default 'user' check (role in ('admin', 'management', 'accountant', 'user')),
  constraint signin_pkey primary key (id),
  constraint signin_email_unique unique(email)
) TABLESPACE pg_default;

-- 2. Create index on email for faster lookups
CREATE INDEX IF NOT EXISTS idx_signin_email ON public.signin(email);

-- 3. Insert test users
INSERT INTO public.signin (email, password, "Name", role) VALUES
('admin@wastefreebd.com', 'admin123', 'Admin User', 'admin'),
('manager@wastefreebd.com', 'manager123', 'Manager User', 'management'),
('accountant@wastefreebd.com', 'accountant123', 'Accountant User', 'accountant'),
('user@wastefreebd.com', 'user123', 'Regular User', 'user')
ON CONFLICT (email) DO NOTHING;

-- 4. Enable Row Level Security (optional but recommended)
ALTER TABLE public.signin ENABLE ROW LEVEL SECURITY;

-- 5. Create a policy to allow public access for authentication
CREATE POLICY "Allow public signin" ON public.signin
  FOR SELECT
  USING (true);

-- You can adjust these policies based on your security requirements
